name: fastly deploy main

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    
    env: # 環境変数としてシークレットを設定
      TOKEN: ${{ secrets.TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get list of changed files
      id: getfile
      run: |
        echo "Changed files:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }}
        files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs)
        echo "changed_files=${files}" >> $GITHUB_ENV
    - name: test
      run: echo $changed_files
    
    - name: Install jq
      run: sudo apt update; sudo apt -y install jq curl

    - name: deploy to fastly
      run: ls; 

