name: fastly deploy main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env: # 環境変数としてシークレットを設定
      FASTLY_API_KEY: ${{ secrets.TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GCSKEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # fetch all history so diffs can be computed

    - name: Get list of changed files
      run: |
        echo "Changed files:"
        changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs)
        echo "Changed files are $changed_files"
        echo "changed_files=$changed_files" >> $GITHUB_ENV

    #- name: Print list of changed files
    #  run: echo "List of changed files: $changed_files"

    - name: Install jq
      run: sudo apt update && sudo apt install -y jq curl wget unzip

    - name: Get terraform
      run: pwd; cd /tmp/; wget  https://releases.hashicorp.com/terraform/1.4.5/terraform_1.4.5_linux_amd64.zip && unzip terraform_1.4.5_linux_amd64.zip && sudo mv terraform /usr/local/bin/; sudo chmod a+x /usr/local/bin/terraform

    - name: terraform apply
      run: cd terraform && pwd; /usr/local/bin/terraform version; /usr/local/bin/terraform init; find . ;  /usr/local/bin/terraform apply -auto-approve 
