name: fastly deploy main

on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    
    env: # 環境変数としてシークレットを設定
      TOKEN: ${{ secrets.TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: diff
      run: changed_files=$(git diff --name-only HEAD^ HEAD)
          changed_files=$(echo $changed_files | tr '\n' ',')
    - name: test
      run: echo $changed_files
    
    - name: Install jq
      run: sudo apt update; sudo apt -y install jq curl

    - name: deploy to fastly
      run: ls; 

